import {
  SiHtml5,
  SiCss3,
  SiNodedotjs,
  SiJavascript,
  SiBootstrap,
  SiReact,
  SiSass,
  SiExpo,
  SiMysql,
  SiMongodb,
  SiExpress,
  SiRedux,
  SiAngular,
  SiTypescript,
  SiPhp,
  SiPostman,
  SiSymfony,
  SiFirebase,
  SiAndroid,
  SiKotlin,
  SiFlutter,
  SiApple,
  SiSwift,
  SiFigma,
  SiVisualstudiocode,
  SiGooglecloud,
  SiAirtable,
  SiGit,
  SiPrestashop,
  SiWordpress,
  SiAdobexd,
  SiC,
  SiOcaml,
  SiProcessingfoundation,
  SiPython,
  SiJava,
} from 'react-icons/si';
import { FaGlide } from 'react-icons/fa';
export const nivExp = {
  0: 'A venir...',
  1: 'Débutant',
  2: 'Intermédiaire',
  3: 'Experimenté',
};

export const frontend = [
  {
    id: 1,
    nom: 'HTML',
    icon: <SiHtml5 className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 2,
    nom: 'CSS',
    icon: <SiCss3 className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 3,
    nom: 'React.js',
    icon: <SiReact className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 4,
    nom: 'JavaScript',
    icon: <SiJavascript className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 5,
    nom: 'Typescript',
    icon: <SiTypescript className="experience_icon" size={20} />,
    exp: 2,
  },
  {
    id: 6,
    nom: 'Bootstrap',
    icon: <SiBootstrap className="experience_icon" size={20} />,
    exp: 2,
  },
  {
    id: 7,
    nom: 'Sass',
    icon: <SiSass className="experience_icon" size={20} />,
    exp: 1,
  },
  {
    id: 8,
    nom: 'Angular',
    icon: <SiAngular className="experience_icon" size={20} />,
    exp: 0,
  },
];
export const backend = [
  {
    id: 1,
    nom: 'Firebase',
    icon: <SiFirebase className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 2,
    nom: 'MySQL',
    icon: <SiMysql className="experience_icon" size={25} />,
    exp: 3,
  },
  {
    id: 5,
    nom: 'MongoDB',
    icon: <SiMongodb className="experience_icon" size={20} />,
    exp: 2,
  },
  {
    id: 6,
    nom: 'Postman',
    icon: <SiPostman className="experience_icon" size={20} />,
    exp: 2,
  },
  {
    id: 3,
    nom: 'Php',
    icon: <SiPhp className="experience_icon" size={20} />,
    exp: 1,
  },
  {
    id: 4,
    nom: 'Node.js',
    icon: <SiNodedotjs className="experience_icon" size={20} />,
    exp: 1,
  },
  {
    id: 7,
    nom: 'Express',
    icon: <SiExpress className="experience_icon" size={20} />,
    exp: 0,
  },
  {
    id: 8,
    nom: 'Symfony',
    icon: <SiSymfony className="experience_icon" size={20} />,
    exp: 0,
  },
];
export const mobile = [
  {
    id: 1,
    nom: 'React Native',
    icon: <SiReact className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 2,
    nom: 'Expo',
    icon: <SiExpo className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 3,
    nom: 'Redux',
    icon: <SiRedux className="experience_icon" size={25} />,
    exp: 3,
  },
  {
    id: 4,
    nom: 'Flutter',
    icon: <SiFlutter className="experience_icon" size={20} />,
    exp: 0,
  },
  {
    id: 5,
    nom: 'Android',
    icon: <SiAndroid className="experience_icon" size={20} />,
    exp: 1,
  },
  {
    id: 6,
    nom: 'Kotlin',
    icon: <SiKotlin className="experience_icon" size={20} />,
    exp: 1,
  },
  {
    id: 7,
    nom: 'iOS',
    icon: <SiApple className="experience_icon" size={25} />,
    exp: 0,
  },
  {
    id: 8,
    nom: 'Swift',
    icon: <SiSwift className="experience_icon" size={25} />,
    exp: 0,
  },
];
export const outils = [
  {
    id: 1,
    nom: 'Figma',
    icon: <SiFigma className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 2,
    nom: 'VScode',
    icon: <SiVisualstudiocode className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 3,
    nom: 'Git',
    icon: <SiGit className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 4,
    nom: 'GoogleCloud',
    icon: <SiGooglecloud className="experience_icon" size={20} />,
    exp: 2,
  },
  {
    id: 5,
    nom: 'Airtable',
    icon: <SiAirtable className="experience_icon" size={20} />,
    exp: 1,
  },
  {
    id: 6,
    nom: 'Adobde Xd',
    icon: <SiAdobexd className="experience_icon" size={20} />,
    exp: 1,
  },
  {
    id: 7,
    nom: 'Wordpress',
    icon: <SiWordpress className="experience_icon" size={25} />,
    exp: 2,
  },
  {
    id: 8,
    nom: 'Prestashop',
    icon: <SiPrestashop className="experience_icon" size={25} />,
    exp: 0,
  },
];
export const autres = [
  {
    id: 1,
    nom: 'C',
    icon: <SiC className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 2,
    nom: 'OCaml',
    icon: <SiOcaml className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 3,
    nom: 'Processing!',
    icon: <SiProcessingfoundation className="experience_icon" size={20} />,
    exp: 3,
  },
  {
    id: 4,
    nom: 'Python',
    icon: <SiPython className="experience_icon" size={20} />,
    exp: 2,
  },
  {
    id: 5,
    nom: 'Java',
    icon: <SiJava className="experience_icon" size={30} />,
    exp: 1,
  },
  {
    id: 6,
    nom: 'Glide',
    icon: <FaGlide className="experience_icon" size={20} />,
    exp: 1,
  },
  {
    id: 7,
    nom: 'Adalo',
    icon: <SiAngular className="experience_icon" size={20} />,
    exp: 2,
  },
];
